### ISSUE TITLE
Prevent the creation of users with no name

### ISSUE THREAD

**Issue by tudorache** [protegeproject/webprotege#132]
Somehow user instances with name=null make it into the metaproject and a NullPointerException is thrown when webprotege starts in tomcat. 

We should prevent the creation of users with null name, and also add defensive code, in case they are already present in the metaproject.

Apr 17, 2014 1:35:02 PM org.apache.catalina.core.ApplicationContext log
SEVERE: Exception while dispatching incoming RPC call
com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract edu.stanford.bmir.protege.web.shared.dispatch.DispatchServiceResultContainer edu.stanford.bmir.protege.web.client.dispatch.DispatchService.executeAction(edu.stanford.bmir.protege.web.shared.dispatch.Action) throws edu.stanford.bmir.protege.web.client.dispatch.ActionExecutionException,edu.stanford.bmir.protege.web.shared.permissions.PermissionDeniedException' threw an unexpected exception: java.lang.NullPointerException
    at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:389)
    at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:579)
    at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208)
    at edu.stanford.bmir.protege.web.server.WebProtegeRemoteServiceServlet.processCall(WebProtegeRemoteServiceServlet.java:151)
    at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
    at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at edu.stanford.bmir.protege.web.server.filter.WebProtegeWebAppFilter.doFilter(WebProtegeWebAppFilter.java:65)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
    at org.apache.coyote.ajp.AjpAprProcessor.process(AjpAprProcessor.java:427)
    at org.apache.coyote.ajp.AjpAprProtocol$AjpConnectionHandler.process(AjpAprProtocol.java:384)
    at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1584)
    at java.lang.Thread.run(Thread.java:619)
Caused by: java.lang.NullPointerException
    at edu.stanford.smi.protege.server.metaproject.impl.UserImpl.equals(UserImpl.java:124)
    at java.util.HashMap.put(HashMap.java:376)
    at java.util.HashSet.add(HashSet.java:200)
    at edu.stanford.smi.protege.server.metaproject.impl.MetaProjectImpl.getWrappedInstances(MetaProjectImpl.java:124)
    at edu.stanford.smi.protege.server.metaproject.impl.MetaProjectImpl.getUsers(MetaProjectImpl.java:149)
    at edu.stanford.smi.protege.server.metaproject.impl.PolicyImpl.getUserByName(PolicyImpl.java:72)
    at edu.stanford.bmir.protege.web.server.LocalMetaProjectManager.getListableReadableProjects(LocalMetaProjectManager.java:118)
    at edu.stanford.bmir.protege.web.server.dispatch.handlers.GetAvailableProjectsHandler.execute(GetAvailableProjectsHandler.java:39)
    at edu.stanford.bmir.protege.web.server.dispatch.handlers.GetAvailableProjectsHandler.execute(GetAvailableProjectsHandler.java:23)
    at edu.stanford.bmir.protege.web.server.dispatch.impl.DefaultDispatchServiceExecutor.execute(DefaultDispatchServiceExecutor.java:34)
    at edu.stanford.bmir.protege.web.server.dispatch.impl.DispatchServiceImpl.executeAction(DispatchServiceImpl.java:35)
    at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:561)
    ... 22 more

**Comment by matthewhorridge** [comment]
No longer possible to create users with null names.
