### ISSUE TITLE
Updating sharing settings sometimes fails

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/webprotege#269]
The logs contain this following trace

```java
Caused by: java.lang.IllegalArgumentException: null value
	at edu.stanford.smi.protege.model.framestore.ArgumentCheckingFrameStore.assertNotNull(ArgumentCheckingFrameStore.java:25)
	at edu.stanford.smi.protege.model.framestore.ArgumentCheckingFrameStore.checkValue(ArgumentCheckingFrameStore.java:82)
	at edu.stanford.smi.protege.model.framestore.ArgumentCheckingFrameStore.checkValues(ArgumentCheckingFrameStore.java:97)
	at edu.stanford.smi.protege.model.framestore.ArgumentCheckingFrameStore.setDirectOwnSlotValues(ArgumentCheckingFrameStore.java:193)
	at edu.stanford.smi.protege.model.framestore.ChangeMonitorFrameStore.setDirectOwnSlotValues(ChangeMonitorFrameStore.java:76)
	at edu.stanford.smi.protege.model.framestore.cleandispatch.DefaultDispatch.setDirectOwnSlotValues(DefaultDispatch.java:13)
	at edu.stanford.smi.protege.model.framestore.cleandispatch.CleanDispatchFrameStore.setDirectOwnSlotValues(CleanDispatchFrameStore.java:36)
	at edu.stanford.smi.protege.model.framestore.FrameStoreAdapter.setDirectOwnSlotValues(FrameStoreAdapter.java:273)
	at edu.stanford.smi.protege.model.framestore.FrameStoreAdapter.setDirectOwnSlotValues(FrameStoreAdapter.java:273)
	at edu.stanford.smi.protege.model.DefaultKnowledgeBase.setDirectOwnSlotValues(DefaultKnowledgeBase.java:245)
	at edu.stanford.smi.protege.model.DefaultFrame.setDirectOwnSlotValues(DefaultFrame.java:390)
	at edu.stanford.smi.protege.server.metaproject.impl.WrappedProtegeInstanceImpl.setSlotValuesAsProtegeInstances(WrappedProtegeInstanceImpl.java:67)
	at edu.stanford.smi.protege.server.metaproject.impl.GroupImpl.setMembers(GroupImpl.java:31)
	at edu.stanford.bmir.protege.web.server.SharingSettingsServiceImplP3Delegate.createAllowedGroupOperationsFromSharingSettings(SharingSettingsServiceImplP3Delegate.java:163)
	at edu.stanford.bmir.protege.web.server.SharingSettingsServiceImplP3Delegate.updateSharingSettings(SharingSettingsServiceImplP3Delegate.java:148)
	at edu.stanford.bmir.protege.web.server.SharingSettingsManager.updateSharingSettings(SharingSettingsManager.java:52)
	at edu.stanford.bmir.protege.web.server.SharingSettingsServiceImpl.updateSharingSettings(SharingSettingsServiceImpl.java:21)
	at sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
	... 23 more
```

**Comment by matthewhorridge** [comment]
This exception is thrown if an email address of an existing account is used.  See also #270.

**Comment by matthewhorridge** [comment]
Fixed.
