### ISSUE TITLE
Updating sharing settings fails if an email address of an existing user is specified rather than the user name

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/webprotege#270]
This is a typical trace (with the email address replaced)

```java
edu.stanford.bmir.protege.web.shared.user.UserEmailAlreadyExistsException: User email address already exists: the.address@the.email.domain
	at edu.stanford.bmir.protege.web.server.LocalMetaProjectManager.registerUser(LocalMetaProjectManager.java:97)
	at edu.stanford.bmir.protege.web.server.AccessPolicyManager.createTemporaryAccountForInvitation(AccessPolicyManager.java:568)
	at edu.stanford.bmir.protege.web.server.SharingSettingsServiceImplP3Delegate.sendEmailInvitation(SharingSettingsServiceImplP3Delegate.java:206)
	at edu.stanford.bmir.protege.web.server.SharingSettingsServiceImplP3Delegate.createUsersBySharingSettingMap(SharingSettingsServiceImplP3Delegate.java:186)
	at edu.stanford.bmir.protege.web.server.SharingSettingsServiceImplP3Delegate.updateSharingSettings(SharingSettingsServiceImplP3Delegate.java:146)
	at edu.stanford.bmir.protege.web.server.SharingSettingsManager.updateSharingSettings(SharingSettingsManager.java:52)
	at edu.stanford.bmir.protege.web.server.SharingSettingsServiceImpl.updateSharingSettings(SharingSettingsServiceImpl.java:21)
	at sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
	at edu.stanford.bmir.protege.web.server.WebProtegeRemoteServiceServlet.processCall(WebProtegeRemoteServiceServlet.java:151)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at edu.stanford.bmir.protege.web.server.filter.WebProtegeWebAppFilter.doFilter(WebProtegeWebAppFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.ajp.AjpAprProcessor.process(AjpAprProcessor.java:427)
	at org.apache.coyote.ajp.AjpAprProtocol$AjpConnectionHandler.process(AjpAprProtocol.java:384)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1584)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by matthewhorridge** [comment]
Fixed.  For the time being, adding email addresses is not supported.
