### ISSUE TITLE
NoClassDefFoundError: Could not initialize class [...]app.WebProtegeApplicationContext

### ISSUE THREAD

**Issue by tudorache** [protegeproject/webprotege#309]
Reported by multiple people on the mailing list.

One of the configurations:
WebProtege: 2.5.0
Server version: Apache Tomcat/8.0.20
OS Name:        Windows Server 2012
OS Version:     6.2
JVM Version:    1.8.0_40-b26 

In Classes portlet, clicked "Create" button, resulting in error message: "There was a problem communicating with the server and the operation could not be completed. Please check your network connection and try again"

Stack trace from tomcat8-stderr.2015-03-30.log: 
```
2015-03-30 13:16:16 Commons Daemon procrun stderr initialized
30-Mar-2015 13:16:23.851 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.20
...
[WebProtege] 1 projects are now being accessed                                                                                                                                       [Mon Mar 30 13:18:27 PDT 2015]
[WebProtege] .... loaded project in 7548 ms                                                                                                                                          [Mon Mar 30 13:18:27 PDT 2015]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[WebProtege] ***** SEVERE *****                                                                                                                                                      [Mon Mar 30 13:19:01 PDT 2015]
             An unexpected exception was thrown on the server
             
             Date and time: Mon Mar 30 13:19:01 PDT 2015
             
             User: paul
             email: [scrubbed]@gmail.com
             groups:
             4ebc699e-0ec9-4fbf-b938-384733f57bda_Writers
             World
             Request URI: /webprotege/webprotege/dispatchservice
             Remote address: 127.0.0.1
             Remote host: 127.0.0.1
             
             Headers:
             host: localhost
             user-agent: Mozilla/5.0 (Windows NT 6.2; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0
             accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
             accept-language: en-US,en;q=0.5
             accept-encoding: gzip, deflate
             content-type: text/x-gwt-rpc; charset=utf-8
             x-gwt-permutation: F84EB2384AFF7B4B1D18EB03A8346CD4
             x-gwt-module-base: http://localhost/webprotege/webprotege/
             referer: http://localhost/webprotege/
             content-length: 521
             cookie: JSESSIONID=243BCE92AA8A65076255796D542A7667; __utma=111872281.1227417880.1426636813.1427504251.1427746683.7;
             __utmz=111872281.1426636813.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utmc=111872281; __utmb=111872281.1.10.1427746683; __utmt=1
             connection: keep-alive
             pragma: no-cache
             cache-control: no-cache
             
             
             Message: Service method 'public abstract edu.stanford.bmir.protege.web.shared.dispatch.DispatchServiceResultContainer
             edu.stanford.bmir.protege.web.client.dispatch.DispatchService.executeAction(edu.stanford.bmir.protege.web.shared.dispatch.Action) throws
             edu.stanford.bmir.protege.web.client.dispatch.ActionExecutionException,edu.stanford.bmir.protege.web.shared.permissions.PermissionDeniedException' threw an
             unexpected exception: java.lang.ExceptionInInitializerError
             
             Stack trace:
             
             com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract
             edu.stanford.bmir.protege.web.shared.dispatch.DispatchServiceResultContainer
             edu.stanford.bmir.protege.web.client.dispatch.DispatchService.executeAction(edu.stanford.bmir.protege.web.shared.dispatch.Action) throws
             edu.stanford.bmir.protege.web.client.dispatch.ActionExecutionException,edu.stanford.bmir.protege.web.shared.permissions.PermissionDeniedException' threw an
             unexpected exception: java.lang.ExceptionInInitializerError
             at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:389)
             at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:579)
             at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208)
             at edu.stanford.bmir.protege.web.server.WebProtegeRemoteServiceServlet.processCall(WebProtegeRemoteServiceServlet.java:151)
             at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
             at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
             at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
             at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
             at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
             at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
             at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
             at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
             at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
             at edu.stanford.bmir.protege.web.server.filter.WebProtegeWebAppFilter.doFilter(WebProtegeWebAppFilter.java:65)
             at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
             at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
             at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
             at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
             at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
             at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
             at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
             at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
             at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
             at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
             at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
             at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
             at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:285)
             at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2439)
             at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2428)
             at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
             at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
             at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
             at java.lang.Thread.run(Unknown Source)
             Caused by: java.lang.ExceptionInInitializerError
             at
             edu.stanford.bmir.protege.web.server.crud.persistence.ProjectEntityCrudKitSettingsRepositoryManager.getRepository(ProjectEntityCrudKitSettingsRepositoryManager.java:18)
             at edu.stanford.bmir.protege.web.server.crud.ProjectEntityCrudKitHandlerCache.getCurrentSettings(ProjectEntityCrudKitHandlerCache.java:41)
             at edu.stanford.bmir.protege.web.server.crud.ProjectEntityCrudKitHandlerCache.getHandler(ProjectEntityCrudKitHandlerCache.java:33)
             at edu.stanford.bmir.protege.web.server.owlapi.OWLAPIProject.getEntityCrudKitHandler(OWLAPIProject.java:360)
             at edu.stanford.bmir.protege.web.server.owlapi.OWLAPIProject.getEntityCreator(OWLAPIProject.java:348)
             at edu.stanford.bmir.protege.web.server.owlapi.OWLAPIProject.applyChanges(OWLAPIProject.java:454)
             at edu.stanford.bmir.protege.web.server.dispatch.AbstractProjectChangeHandler.execute(AbstractProjectChangeHandler.java:29)
             at edu.stanford.bmir.protege.web.server.dispatch.AbstractHasProjectActionHandler.execute(AbstractHasProjectActionHandler.java:54)
             at edu.stanford.bmir.protege.web.server.dispatch.impl.DefaultDispatchServiceExecutor.execute(DefaultDispatchServiceExecutor.java:34)
             at edu.stanford.bmir.protege.web.server.dispatch.impl.DispatchServiceImpl.executeAction(DispatchServiceImpl.java:35)
             at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
             at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
             at java.lang.reflect.Method.invoke(Unknown Source)
             at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:561)
             ... 31 more
             Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: file [C:\Program Files (x86)\Apache
             Software Foundation\Tomcat 8.0\webapps\webprotege\WEB-INF\classes\edu\stanford\bmir\protege\web\server\comparator\OntologyAnnotationsComparator.class]; nested
             exception is java.lang.ArrayIndexOutOfBoundsException: 51966
             at
             org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:262)
             at org.springframework.data.repository.config.RepositoryConfigurationSourceSupport.getCandidates(RepositoryConfigurationSourceSupport.java:68)
             at
             org.springframework.data.repository.config.RepositoryConfigurationExtensionSupport.getRepositoryConfigurations(RepositoryConfigurationExtensionSupport.java:53)
             at
             org.springframework.data.repository.config.RepositoryBeanDefinitionRegistrarSupport.registerBeanDefinitions(RepositoryBeanDefinitionRegistrarSupport.java:99)
             at org.springframework.context.annotation.ConfigurationClassParser.processImport(ConfigurationClassParser.java:332)
             at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:225)
             at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:147)
             at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:133)
             at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:286)
             at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:227)
             at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:623)
             at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:454)
             at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:73)
             at edu.stanford.bmir.protege.web.server.app.WebProtegeApplicationContext.<clinit>(WebProtegeApplicationContext.java:19)
             ... 45 more
             Caused by: java.lang.ArrayIndexOutOfBoundsException: 51966
             at org.springframework.asm.ClassReader.readUTF8(Unknown Source)
             at org.springframework.asm.ClassReader.readClass(Unknown Source)
             at org.springframework.asm.ClassReader.accept(Unknown Source)
             at org.springframework.asm.ClassReader.accept(Unknown Source)
             at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:59)
             at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:80)
             at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:101)
             at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:76)
             at org.springframework.core.type.filter.AbstractTypeHierarchyTraversingFilter.match(AbstractTypeHierarchyTraversingFilter.java:105)
             at org.springframework.core.type.filter.AbstractTypeHierarchyTraversingFilter.match(AbstractTypeHierarchyTraversingFilter.java:95)
             at
             org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.isCandidateComponent(ClassPathScanningCandidateComponentProvider.java:305)
             at
             org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:239)
             ... 58 more 
```

**Comment by tudorache** [comment]
Fixed in 2.6.0.
