### ISSUE TITLE
Error at initialization by guice: Error in custom provider, java.lang.IllegalStateException: This is a proxy used to support circular references involving constructors. 

### ISSUE THREAD

**Issue by tudorache** [protegeproject/webprotege#350]
Error reported by user. See attached log.
[log-0408.txt](https://github.com/protegeproject/webprotege/files/214012/log-0408.txt)

Might be related to this google guice bug:
https://github.com/google/guice/issues/550

```
Server version:        Apache Tomcat/8.0.33
Server built:          Mar 18 2016 20:31:49 UTC
Server number:         8.0.33.0
OS Name:               Windows Server 2012 R2
OS Version:            6.3
Architecture:          amd64
Java Home:             C:\Program Files\Java\jre1.8.0_77
JVM Version:           1.8.0_77-b03
JVM Vendor:            Oracle Corporation
CATALINA_BASE:         C:\apache-tomcat-8.0.33
CATALINA_HOME:         C:\apache-tomcat-8.0.33
```

```
[WebProtege] Fri Apr 08 18:27:47 EDT 2016
             Overriding mail.smtp.host with system property
java.lang.ExceptionInInitializerError
        at edu.stanford.bmir.protege.web.server.WebProtegeInitializer.contextInitialized(WebProtegeInitializer.java:24)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4811)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5251)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: com.google.inject.CreationException: Guice creation errors:
 (see log for full output)
```

**Comment by matthewhorridge** [comment]
The error is thrown by the MailPropertiesProvider if a SecurityException is thrown when trying to access the System Properties.  This is because the MailPropertiesProvider attempts to log the problem before Guice has had change to set up the default WebProtege logger.
