### ISSUE TITLE
[3.0.0] Unable to upload and merge a file

### ISSUE THREAD

**Issue by bdecarne** [protegeproject/webprotege#446]
Hi,

In webprotege 3.0.0 i try to use the "Project > Upload & merge" feature. It does not work, with the following error : 

```
webprotege_1  | 2018-02-15 17:11:22.247  INFO   Received upload request from UserId{admin} at 192.168.64.1 
webprotege_1  | 2018-02-15 17:11:22.316  INFO   File size is 6219401 bytes. Stored uploaded file with name upload-7926036265256804857 
webprotege_1  | 15-Feb-2018 17:11:29.769 SEVERE [http-nio-8080-exec-2] edu.stanford.bmir.protege.web.server.dispatch.impl.DispatchServiceExecutorImpl.execute An error occurred whilst executing an action
webprotege_1  |  java.lang.NullPointerException
webprotege_1  |         at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
webprotege_1  |         at edu.stanford.bmir.protege.web.server.change.ChangeApplicationResult.<init>(ChangeApplicationResult.java:37)
webprotege_1  |         at edu.stanford.bmir.protege.web.server.project.ChangeManager.applyChanges(ChangeManager.java:295)
webprotege_1  |         at edu.stanford.bmir.protege.web.server.merge.MergeUploadedProjectActionHandler.applyChanges(MergeUploadedProjectActionHandler.java:95)
webprotege_1  |         at edu.stanford.bmir.protege.web.server.merge.MergeUploadedProjectActionHandler.execute(MergeUploadedProjectActionHandler.java:87)
webprotege_1  |         at edu.stanford.bmir.protege.web.server.merge.MergeUploadedProjectActionHandler.execute(MergeUploadedProjectActionHandler.java:41)
webprotege_1  |         at edu.stanford.bmir.protege.web.server.dispatch.impl.DispatchServiceExecutorImpl.execute(DispatchServiceExecutorImpl.java:71)
webprotege_1  |         at edu.stanford.bmir.protege.web.server.dispatch.impl.DispatchServiceImpl.executeAction(DispatchServiceImpl.java:50)
webprotege_1  |         at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
webprotege_1  |         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
webprotege_1  |         at java.lang.reflect.Method.invoke(Method.java:498)
webprotege_1  |         at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
webprotege_1  |         at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
webprotege_1  |         at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
webprotege_1  |         at edu.stanford.bmir.protege.web.server.app.WebProtegeRemoteServiceServlet.processCall(WebProtegeRemoteServiceServlet.java:61)
webprotege_1  |         at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
webprotege_1  |         at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
webprotege_1  |         at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
webprotege_1  |         at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
webprotege_1  |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
webprotege_1  |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
webprotege_1  |         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
webprotege_1  |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
webprotege_1  |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
webprotege_1  |         at edu.stanford.bmir.protege.web.server.filter.WebProtegeWebAppFilter.doFilter(WebProtegeWebAppFilter.java:75)
webprotege_1  |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
webprotege_1  |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
webprotege_1  |         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
webprotege_1  |         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
webprotege_1  |         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
webprotege_1  |         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
webprotege_1  |         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
webprotege_1  |         at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
webprotege_1  |         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
webprotege_1  |         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
webprotege_1  |         at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
webprotege_1  |         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
webprotege_1  |         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
webprotege_1  |         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
webprotege_1  |         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
webprotege_1  |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
webprotege_1  |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
webprotege_1  |         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
webprotege_1  |         at java.lang.Thread.run(Thread.java:748)
```

The file used can be successfully used when i create a new project.

Blaise

**Comment by matthewhorridge** [comment]
Thanks for the bug report.  I can reproduce this.
