### ISSUE TITLE
Allow email addresses to be reused over multiple accounts

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/webprotege#47]
At the moment the relationship between account name and email address is one-to-one.  It should be possible to specify the same email address for multiple accounts.  Some consideration is needed, because there is some code which looks up user accounts by email address!

`edu.stanford.bmir.protege.web.shared.user.UserEmailAlreadyExistsException: User email address already exists: darkoandr@yahoo.com
    at edu.stanford.bmir.protege.web.server.LocalMetaProjectManager.registerUser(LocalMetaProjectManager.java:100)
    at edu.stanford.bmir.protege.web.server.AccessPolicyManager.createTemporaryAccountForInvitation(AccessPolicyManager.java:666)
    at edu.stanford.bmir.protege.web.server.SharingSettingsServiceImplP3Delegate.sendEmailInvitation(SharingSettingsServiceImplP3Delegate.java:206)
    at edu.stanford.bmir.protege.web.server.SharingSettingsServiceImplP3Delegate.createUsersBySharingSettingMap(SharingSettingsServiceImplP3Delegate.java:186)
    at edu.stanford.bmir.protege.web.server.SharingSettingsServiceImplP3Delegate.updateSharingSettings(SharingSettingsServiceImplP3Delegate.java:146)
    at edu.stanford.bmir.protege.web.server.SharingSettingsManager.updateSharingSettings(SharingSettingsManager.java:52)
    at edu.stanford.bmir.protege.web.server.SharingSettingsServiceImpl.updateSharingSettings(SharingSettingsServiceImpl.java:21)`

**Comment by matthewhorridge** [comment]
We don't allow this as it's a security hazard.
