### ISSUE TITLE
URI is not hierarchical exception

### ISSUE THREAD

**Issue by stephenetyler** [protegeproject/webprotege#544]
I built webprotege-4.0.0-SNAPSHOT yesterday, but I received this exception after trying to access the web site...

2018-09-11 17:30:22.728  INFO   1 projects are now being accessed
2018-09-11 17:30:22.728  INFO   ProjectId{cad0d4d9-77b3-4ec3-afe6-7291146d40e4} was loaded in 1036 ms due to request by UserId{admin}
2018-09-11 17:30:22.728  INFO   Memory Usage: Using 77 MB of 910 MB (8.52%) [832 MB free]
2018-09-11 17:30:22.824  ERROR  An error occurred whilst executing an action
java.lang.IllegalArgumentException: URI is not hierarchical
        at java.io.File.<init>(File.java:418)
        at edu.stanford.bmir.protege.web.server.perspective.PerspectiveDataCopier.copyDefaultPerspectiveData(PerspectiveDataCopier.java:38)
        at edu.stanford.bmir.protege.web.server.perspective.PerspectiveFileManager.copyDefaultPerspectiveDataIfNecessary(PerspectiveFileManager.java:54)
        at edu.stanford.bmir.protege.web.server.perspective.PerspectiveFileManager.getDefaultPerspectiveLayout(PerspectiveFileManager.java:46)
        at edu.stanford.bmir.protege.web.server.perspective.PerspectiveLayoutStoreImpl.getPerspectiveFile(PerspectiveLayoutStoreImpl.java:80)
        at edu.stanford.bmir.protege.web.server.perspective.PerspectiveLayoutStoreImpl.getPerspectiveFile(PerspectiveLayoutStoreImpl.java:72)
        at edu.stanford.bmir.protege.web.server.perspective.PerspectiveLayoutStoreImpl.getPerspectiveLayout(PerspectiveLayoutStoreImpl.java:40)
        at edu.stanford.bmir.protege.web.server.perspective.GetPerspectiveLayoutActionHandler.execute(GetPerspectiveLayoutActionHandler.java:50)
        at edu.stanford.bmir.protege.web.server.perspective.GetPerspectiveLayoutActionHandler.execute(GetPerspectiveLayoutActionHandler.java:23)
        at edu.stanford.bmir.protege.web.server.dispatch.impl.DispatchServiceExecutorImpl.execute(DispatchServiceExecutorImpl.java:73)
        at edu.stanford.bmir.protege.web.server.dispatch.DispatchServlet.executeAction(DispatchServlet.java:49)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
        at edu.stanford.bmir.protege.web.server.app.WebProtegeRemoteServiceServlet.processCall(WebProtegeRemoteServiceServlet.java:64)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
        at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at edu.stanford.bmir.protege.web.server.filter.WebProtegeWebAppFilter.doFilter(WebProtegeWebAppFilter.java:75)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:770)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

Its the same issue this person is experiencing - http://protege-project.136.n4.nabble.com/Building-webprotege-3-from-source-td4670411.html

Any  ideas?

Thanks
-stephen

**Comment by imrankhan1984** [comment]
Hi, 
I have the same error which building WebProtégé 4.0.0:20180925:fac8129. I'm able to compile successfully from the source but after deploying the war file, when I create a project, I get "URI is not hierarchical" error.

java.lang.IllegalArgumentException: URI is not hierarchical
        at java.io.File.<init>(File.java:418)
        at edu.stanford.bmir.protege.web.server.perspective.PerspectiveDataCopier.copyDefaultPerspectiveData(PerspectiveDataCopier.java:38)
        at edu.stanford.bmir.protege.web.server.perspective.PerspectiveFileManager.copyDefaultPerspectiveDataIfNecessary(PerspectiveFileManager.java:54)
        at edu.stanford.bmir.protege.web.server.perspective.PerspectiveFileManager.getDefaultPerspectiveLayout(PerspectiveFileManager.java:46)
        at edu.stanford.bmir.protege.web.server.perspective.PerspectiveLayoutStoreImpl.getPerspectiveFile(PerspectiveLayoutStoreImpl.java:80)
        at edu.stanford.bmir.protege.web.server.perspective.PerspectiveLayoutStoreImpl.getPerspectiveFile(PerspectiveLayoutStoreImpl.java:72)
        at edu.stanford.bmir.protege.web.server.perspective.PerspectiveLayoutStoreImpl.getPerspectiveLayout(PerspectiveLayoutStoreImpl.java:40)
        at edu.stanford.bmir.protege.web.server.perspective.GetPerspectiveLayoutActionHandler.execute(GetPerspectiveLayoutActionHandler.java:50)
        at edu.stanford.bmir.protege.web.server.perspective.GetPerspectiveLayoutActionHandler.execute(GetPerspectiveLayoutActionHandler.java:23)
        at edu.stanford.bmir.protege.web.server.dispatch.impl.DispatchServiceExecutorImpl.execute(DispatchServiceExecutorImpl.java:73)
        at edu.stanford.bmir.protege.web.server.dispatch.DispatchServlet.executeAction(DispatchServlet.java:49)
        at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
        at edu.stanford.bmir.protege.web.server.app.WebProtegeRemoteServiceServlet.processCall(WebProtegeRemoteServiceServlet.java:64)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
        at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at edu.stanford.bmir.protege.web.server.filter.WebProtegeWebAppFilter.doFilter(WebProtegeWebAppFilter.java:75)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:491)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:764)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1388)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
2018-09-26 16:03:54.808  INFO   [34mPurged project: 9848265f-5035-4cad-9b1b-4a1768753268.  0 projects are now being accessed.[0;39m

**Comment by matthewhorridge** [comment]
We can reproduce this and will aim for a fix by the end of this week

**Comment by stephenetyler** [comment]
Much appreciated.  Thanks for your hard work.
