### ISSUE TITLE
Building WebProtege fails: cannot find artifact

### ISSUE THREAD

**Issue by cogan-shimizu-wsu** [protegeproject/webprotege#581]
`[ERROR] Failed to execute goal on project webprotege-server: Could not resolve dependencies for project edu.stanford.protege:webprotege-server:war:4.0.0-SNAPSHOT: Could not find artifact edu.stanford.protege:graphtree:jar:1.0.1-SNAPSHOT in oss-sonatype (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]`

This occurs even when using 
`mvn clean install -U`

Below is the output for
`mvn clean install -e -X -U`

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] webprotege ........................................ SUCCESS [0.687s]
[INFO] webprotege-shared-core ............................ SUCCESS [3.246s]
[INFO] webprotege-shared ................................. SUCCESS [13.370s]
[INFO] webprotege-server-core ............................ SUCCESS [21.021s]
[INFO] webprotege-client ................................. SUCCESS [9:07.463s]
[INFO] webprotege-server ................................. FAILURE [4.532s]
[INFO] webprotege-cli .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9:51.067s
[INFO] Finished at: Thu Oct 18 16:14:08 EDT 2018
[INFO] Final Memory: 98M/2150M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project webprotege-server: Could not resolve dependencies for project edu.stanford.protege:webprotege-server:war:4.0.0-SNAPSHOT: Could not find artifact edu.stanford.protege:graphtree:jar:1.0.1-SNAPSHOT in oss-sonatype (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project webprotege-server: Could not resolve dependencies for project edu.stanford.protege:webprotege-server:war:4.0.0-SNAPSHOT: Could not find artifact edu.stanford.protege:graphtree:jar:1.0.1-SNAPSHOT in oss-sonatype (https://oss.sonatype.org/content/repositories/snapshots/)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:210)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:117)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:258)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:201)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project edu.stanford.protege:webprotege-server:war:4.0.0-SNAPSHOT: Could not find artifact edu.stanford.protege:graphtree:jar:1.0.1-SNAPSHOT in oss-sonatype (https://oss.sonatype.org/content/repositories/snapshots/)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:189)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:185)
        ... 22 more
Caused by: org.sonatype.aether.resolution.DependencyResolutionException: Could not find artifact edu.stanford.protege:graphtree:jar:1.0.1-SNAPSHOT in oss-sonatype (https://oss.sonatype.org/content/repositories/snapshots/)
        at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:375)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:183)
        ... 23 more
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not find artifact edu.stanford.protege:graphtree:jar:1.0.1-SNAPSHOT in oss-sonatype (https://oss.sonatype.org/content/repositories/snapshots/)
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
        at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:358)
        ... 24 more
Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact edu.stanford.protege:graphtree:jar:1.0.1-SNAPSHOT in oss-sonatype (https://oss.sonatype.org/content/repositories/snapshots/)
        at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:947)
        at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:939)
        at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:669)
        at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :webprotege-server
```
I'm not really sure how to go about fixing this. I was using this issue to build webprotege. #465

**Comment by cogan-shimizu-wsu** [comment]
I was able to change the dependency here: https://github.com/protegeproject/webprotege/blob/master/pom.xml#L50
to be the 1.0.0 snapshot as is found here:
https://oss.sonatype.org/content/repositories/snapshots/edu/stanford/protege/graphtree/ 
which allows `mvn clean install -e -X -U` to resolve.

**Comment by matthewhorridge** [comment]
Sorry for the late response.  I need to do a fresh non-snapshot build of graph-tree.  Will try to do this today.

**Comment by matthewhorridge** [comment]
You can temporarily change it to 1.1.1, which should work.  Not sure how this wasn't updated without looking into it further.

**Comment by matthewhorridge** [comment]
@cogan-shimizu-wsu are you happy if I close this issue?
