### ISSUE TITLE
java.lang.RuntimeException: Unsupported

### ISSUE THREAD

**Issue by wojtuch** [protegeproject/webprotege#614]
Dear WebProtege Team,

first of all let me thank you for this nice tool!

I am currently setting up an in-house WebProtege for our team but I'm running into issues while browsing the class tree or individuals by class. I managed to investigate that it happens for classes which have relations represented via blank nodes, e.g.:
```
    <owl:Class rdf:about="http://www.namespace.com/my-ontology#Politician">
        <rdfs:subClassOf rdf:resource="http://www.namespace.com/my-ontology#Person"/>
        <ns:hasApiType>
            <rdf:Description>
                <rdfs:label xml:lang="en">Politician</rdfs:label>
                <ns:typeId>politician</ns:typeId>
            </rdf:Description>
        </ns:hasApiType>
```
The error stack trace I see in the server logs doesn't say much:
```
09-Apr-2019 09:09:31.031 SEVERE [http-nio-8080-exec-4] edu.stanford.bmir.protege.web.server.dispatch.impl.DispatchServiceExecutorImpl.execute An error occurred whilst executing an action
 java.lang.RuntimeException: Unsupported
	at edu.stanford.bmir.protege.web.server.renderer.RenderingManager.getRendering(RenderingManager.java:286)
	at edu.stanford.bmir.protege.web.server.frame.AxiomPropertyValueTranslator$AxiomTranslator.visit(AxiomPropertyValueTranslator.java:151)
	at edu.stanford.bmir.protege.web.server.frame.AxiomPropertyValueTranslator$AxiomTranslator.visit(AxiomPropertyValueTranslator.java:83)
	at uk.ac.manchester.cs.owl.owlapi.OWLAnnotationAssertionAxiomImpl.accept(OWLAnnotationAssertionAxiomImpl.java:182)
	at edu.stanford.bmir.protege.web.server.frame.AxiomPropertyValueTranslator.getPropertyValues(AxiomPropertyValueTranslator.java:63)
	at edu.stanford.bmir.protege.web.server.frame.ClassFrameTranslator.translateAxiomsToPropertyValues(ClassFrameTranslator.java:116)
	at edu.stanford.bmir.protege.web.server.frame.ClassFrameTranslator.translateToClassFrame(ClassFrameTranslator.java:83)
	at edu.stanford.bmir.protege.web.server.frame.ClassFrameTranslator.getFrame(ClassFrameTranslator.java:71)
	at edu.stanford.bmir.protege.web.server.frame.NamedIndividualFrameTranslator.translateToNamedIndividualFrame(NamedIndividualFrameTranslator.java:96)
	at edu.stanford.bmir.protege.web.server.frame.NamedIndividualFrameTranslator.getFrame(NamedIndividualFrameTranslator.java:66)
	at edu.stanford.bmir.protege.web.server.frame.GetNamedIndividualFrameActionHandler.execute(GetNamedIndividualFrameActionHandler.java:67)
	at edu.stanford.bmir.protege.web.server.frame.GetNamedIndividualFrameActionHandler.execute(GetNamedIndividualFrameActionHandler.java:28)
	at edu.stanford.bmir.protege.web.server.dispatch.impl.DispatchServiceExecutorImpl.execute(DispatchServiceExecutorImpl.java:71)
	at edu.stanford.bmir.protege.web.server.dispatch.impl.DispatchServiceImpl.executeAction(DispatchServiceImpl.java:50)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
	at edu.stanford.bmir.protege.web.server.app.WebProtegeRemoteServiceServlet.processCall(WebProtegeRemoteServiceServlet.java:61)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at edu.stanford.bmir.protege.web.server.filter.WebProtegeWebAppFilter.doFilter(WebProtegeWebAppFilter.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```
If it matters, the ontology was uploaded (create new project -> create from existing sources).

Is there a way I can use WebProtege in my scenario?

Thanks a ton!
wojtuch

edit:
Desktop Protege Client handles it well and displays the relations:
![image](https://user-images.githubusercontent.com/1650824/55791336-91540700-5abe-11e9-8c78-45c4e72ecaad.png)

**Comment by wojtuch** [comment]
@matthewhorridge thanks for the quick answer! That's a pity.
do you think getting rid of blank nodes and rewriting
```
    <owl:Class rdf:about="http://www.namespace.com/my-ontology#Politician">
        <rdfs:subClassOf rdf:resource="http://www.namespace.com/my-ontology#Person"/>
        <ns:hasApiType>
            <rdf:Description>
                <rdfs:label xml:lang="en">Politician</rdfs:label>
                <ns:typeId>politician</ns:typeId>
            </rdf:Description>
        </ns:hasApiType>
```
to
```
:Politician rdfs:subClassOf :Person .
:Politician ns:hasApiType ns:ApiPoliticianType .
ns:ApiPoliticianType rdfs:label "Politician" .
ns:ApiPoliticianType ns:typeId "politician"
```
would solve the issue and make WebProtege display it properly?

**Comment by matthewhorridge** [comment]
Yes @wojtuch.  I also think that is preferable for SPARQL querying as well (if you want to do that in the end)

**Comment by wojtuch** [comment]
thanks for your assistance @matthewhorridge !
