### ISSUE TITLE
Log files are not being written

### ISSUE THREAD

**Issue by fanavarro** [protegeproject/webprotege#634]
Hi all, I had a local instance of web protege version 3.0.0. It was configured to write the log files in /var/log/weprotege/ folder (default value, actually I had this option commented in the config file).

Recently I have migrated to 4.0.0 beta-2, and the application is writing in the standard output instead of the log files. I have to read catalina.out file in the tomcat logs folder to check the web protege log. I have not changed anything in the configuration files. Should I configure the logs in another way in this new release? It could be that the default option for log files was the standard output in this new version, instead of /var/log/webprotege/?

Thanks for your time.

**Comment by matthewhorridge** [comment]
Hi @fanavarro, by default, WebProtege is configured to write to ```/var/log/webprotege``` on Linux and Mac systems (and ```\ProgramData\WebProtege\Logs``` on Windows systems).  It will also write the logs to std out.  I'm wondering if the logs directory is writeable by the user that tomcat runs under.  Please can you double check this?

**Comment by fanavarro** [comment]
Hi @matthewhorridge, thanks for your answer.

I am running Tomcat as root, so I guess it should be able to write in any directory. I also have set permissions to read, write and execute for everybody in the folder /var/log/webprotege (drwxrwxrwx in linux). 

Moreover, I have specified that this is the log folder in the config file in /etc/webprotege/webprotege.properties with the line `logs.directory=/var/log/webprotege`.

I also have removed the old log files (generated with the previous version 3.0.0) in order to check if the files are regenerated. Nonetheless, when I start tomcat, this folder remains empty.

**Comment by zym1010** [comment]
I have the same issue.

**Comment by dziustino** [comment]
>> <...> in the config file in /etc/webprotege/webprotege.properties with the line `logs.directory=/var/log/webprotege`.


I have the same setup and running webprotege on openshift.
I get error

>  ERROR in ch.qos.logback.core.rolling.RollingFileAppender[webprotege-all] - openFile(logsdir_IS_UNDEFINED/webprotege-all.log,true) call failed. java.io.FileNotFoundException: logsdir_IS_UNDEFINED/webprotege-all.log (No such file or directory)



maybe logs/directory should "specified" in https://github.com/protegeproject/webprotege/blob/master/webprotege-shared-core/src/main/java/edu/stanford/bmir/protege/web/shared/app/WebProtegePropertyName.java ?

p.s. Thank you for your great work

**Comment by kenjkeefe** [comment]
I am trying to to get webprotege 4.0.0 beta-2 running and I get this same error. Here is an output:

`Feb 21, 2020 1:03:16 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat8/common/classes], exists: [false], isDirectory: [false], canRead: [false]
Feb 21, 2020 1:03:16 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat8/common], exists: [false], isDirectory: [false], canRead: [false]
Feb 21, 2020 1:03:16 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat8/server/classes], exists: [false], isDirectory: [false], canRead: [false]
Feb 21, 2020 1:03:16 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat8/server], exists: [false], isDirectory: [false], canRead: [false]
Feb 21, 2020 1:03:16 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat8/shared/classes], exists: [false], isDirectory: [false], canRead: [false]
Feb 21, 2020 1:03:16 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat8/shared], exists: [false], isDirectory: [false], canRead: [false]
Feb 21, 2020 1:03:17 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server version:        Apache Tomcat/8.0.32 (Ubuntu)
Feb 21, 2020 1:03:17 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server built:          Jan 24 2020 16:24:30 UTC
Feb 21, 2020 1:03:17 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server number:         8.0.32.0
Feb 21, 2020 1:03:17 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Name:               Linux
Feb 21, 2020 1:03:17 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Version:            4.4.0-174-generic
Feb 21, 2020 1:03:17 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Architecture:          amd64
Feb 21, 2020 1:03:17 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
Feb 21, 2020 1:03:17 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Version:           1.8.0_242-8u242-b08-0ubuntu3~16.04-b08
Feb 21, 2020 1:03:17 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Vendor:            Private Build
Feb 21, 2020 1:03:17 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_BASE:         /var/lib/tomcat8
Feb 21, 2020 1:03:17 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_HOME:         /usr/share/tomcat8
Feb 21, 2020 1:03:17 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.util.logging.config.file=/var/lib/tomcat8/conf/logging.properties
Feb 21, 2020 1:03:17 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
Feb 21, 2020 1:03:17 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.awt.headless=true
Feb 21, 2020 1:03:17 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Xmx128m
Feb 21, 2020 1:03:17 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -XX:+UseConcMarkSweepGC
Feb 21, 2020 1:03:17 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dfile.encoding=UTF-8
Feb 21, 2020 1:03:17 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dfile.encoding=UTF-8
Feb 21, 2020 1:03:17 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.endorsed.dirs=/usr/share/tomcat8/endorsed
Feb 21, 2020 1:03:17 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dcatalina.base=/var/lib/tomcat8
Feb 21, 2020 1:03:17 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dcatalina.home=/usr/share/tomcat8
Feb 21, 2020 1:03:17 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.io.tmpdir=/tmp/tomcat8-tomcat8-tmp
Feb 21, 2020 1:03:17 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8081"]
Feb 21, 2020 1:03:17 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
Feb 21, 2020 1:03:17 PM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 815 ms
Feb 21, 2020 1:03:17 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
Feb 21, 2020 1:03:17 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.0.32 (Ubuntu)
Feb 21, 2020 1:03:17 PM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deploying configuration descriptor /etc/tomcat8/Catalina/localhost/manager.xml
Feb 21, 2020 1:03:18 PM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Feb 21, 2020 1:03:18 PM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deployment of configuration descriptor /etc/tomcat8/Catalina/localhost/manager.xml has finished in 856 ms
Feb 21, 2020 1:03:18 PM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deploying configuration descriptor /etc/tomcat8/Catalina/localhost/host-manager.xml
Feb 21, 2020 1:03:18 PM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Feb 21, 2020 1:03:18 PM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deployment of configuration descriptor /etc/tomcat8/Catalina/localhost/host-manager.xml has finished in 479 ms
Feb 21, 2020 1:03:18 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat8/webapps/webprotege.war
Feb 21, 2020 1:03:23 PM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
13:03:23,187 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
13:03:23,187 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
13:03:23,187 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/var/lib/tomcat8/webapps/webprotege/WEB-INF/classes/logback.xml]
13:03:23,273 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
13:03:23,290 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [file:/var/lib/tomcat8/webapps/webprotege/WEB-INF/classes/logback.xml] 
13:03:23,290 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 1 minutes
13:03:23,297 |-ERROR in ch.qos.logback.core.joran.conditional.IfAction - Could not find Janino library on the class path. Skipping conditional processing.
13:03:23,297 |-ERROR in ch.qos.logback.core.joran.conditional.IfAction - See also http://logback.qos.ch/codes.html#ifJanino
13:03:23,298 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
13:03:23,305 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [stdout]
13:03:23,360 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
13:03:23,364 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [webprotege]
13:03:23,374 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1454780177 - No compression will be used
13:03:23,376 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1454780177 - Will use the pattern logsdir_IS_UNDEFINED/webprotege.%d{yyyy-MM-dd}.log for the active file
13:03:23,381 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern 'logsdir_IS_UNDEFINED/webprotege.%d{yyyy-MM-dd}.log'.
13:03:23,381 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
13:03:23,382 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Fri Feb 21 13:03:23 CST 2020
13:03:23,385 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[webprotege] - Active log file name: logsdir_IS_UNDEFINED/webprotege.log
13:03:23,385 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[webprotege] - File property is set to [logsdir_IS_UNDEFINED/webprotege.log]
13:03:23,386 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[webprotege] - Failed to create parent directories for [/var/lib/tomcat8/logsdir_IS_UNDEFINED/webprotege.log]
13:03:23,386 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[webprotege] - openFile(logsdir_IS_UNDEFINED/webprotege.log,true) call failed. java.io.FileNotFoundException: logsdir_IS_UNDEFINED/webprotege.log (No such file or directory)
	at java.io.FileNotFoundException: logsdir_IS_UNDEFINED/webprotege.log (No such file or directory)
	at 	at java.io.FileOutputStream.open0(Native Method)
	at 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:204)
	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:127)
	at 	at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:100)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:128)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:107)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:295)
	at 	at ch.qos.logback.classic.util.StatusViaSLF4JLoggerFactory.addStatus(StatusViaSLF4JLoggerFactory.java:32)
	at 	at ch.qos.logback.classic.util.StatusViaSLF4JLoggerFactory.addInfo(StatusViaSLF4JLoggerFactory.java:20)
	at 	at ch.qos.logback.classic.servlet.LogbackServletContainerInitializer.onStartup(LogbackServletContainerInitializer.java:26)
	at 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5253)
	at 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:939)
	at 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1812)
	at 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at 	at java.lang.Thread.run(Thread.java:748)
13:03:23,386 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
13:03:23,386 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [webprotege-all]
13:03:23,387 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@810080851 - No compression will be used
13:03:23,387 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@810080851 - Will use the pattern logsdir_IS_UNDEFINED/webprotege-all.%d{yyyy-MM-dd}.log for the active file
13:03:23,388 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern 'logsdir_IS_UNDEFINED/webprotege-all.%d{yyyy-MM-dd}.log'.
13:03:23,388 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
13:03:23,389 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Fri Feb 21 13:03:23 CST 2020
13:03:23,389 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[webprotege-all] - Active log file name: logsdir_IS_UNDEFINED/webprotege-all.log
13:03:23,389 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[webprotege-all] - File property is set to [logsdir_IS_UNDEFINED/webprotege-all.log]
13:03:23,390 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[webprotege-all] - Failed to create parent directories for [/var/lib/tomcat8/logsdir_IS_UNDEFINED/webprotege-all.log]
13:03:23,390 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[webprotege-all] - openFile(logsdir_IS_UNDEFINED/webprotege-all.log,true) call failed. java.io.FileNotFoundException: logsdir_IS_UNDEFINED/webprotege-all.log (No such file or directory)
	at java.io.FileNotFoundException: logsdir_IS_UNDEFINED/webprotege-all.log (No such file or directory)
	at 	at java.io.FileOutputStream.open0(Native Method)
	at 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:204)
	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:127)
	at 	at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:100)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:128)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:107)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:295)
	at 	at ch.qos.logback.classic.util.StatusViaSLF4JLoggerFactory.addStatus(StatusViaSLF4JLoggerFactory.java:32)
	at 	at ch.qos.logback.classic.util.StatusViaSLF4JLoggerFactory.addInfo(StatusViaSLF4JLoggerFactory.java:20)
	at 	at ch.qos.logback.classic.servlet.LogbackServletContainerInitializer.onStartup(LogbackServletContainerInitializer.java:26)
	at 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5253)
	at 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:939)
	at 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1812)
	at 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at 	at java.lang.Thread.run(Thread.java:748)
13:03:23,390 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [edu.stanford.bmir.protege.web] to INFO
13:03:23,390 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [webprotege] to Logger[edu.stanford.bmir.protege.web]
13:03:23,391 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [stdout] to Logger[edu.stanford.bmir.protege.web]
13:03:23,391 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@52:68 - no applicable action for [turboFilter], current ElementPath  is [[configuration][turboFilter]]
13:03:23,392 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@53:15 - no applicable action for [Name], current ElementPath  is [[configuration][turboFilter][Name]]
13:03:23,392 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@54:17 - no applicable action for [Marker], current ElementPath  is [[configuration][turboFilter][Marker]]
13:03:23,392 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@55:18 - no applicable action for [OnMatch], current ElementPath  is [[configuration][turboFilter][OnMatch]]
13:03:23,392 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
13:03:23,392 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [webprotege-all] to Logger[ROOT]
13:03:23,392 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
13:03:23,393 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@57e1b5ec - Registering current configuration as safe fallback point

Feb 21, 2020 1:03:23 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
Feb 21, 2020 1:03:23 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/webprotege] startup failed due to previous errors
Feb 21, 2020 1:03:23 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
WARNING: The web application [webprotege] appears to have started a thread named [logback-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)
Feb 21, 2020 1:03:23 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /var/lib/tomcat8/webapps/webprotege.war has finished in 4,643 ms
Feb 21, 2020 1:03:23 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-8081"]
Feb 21, 2020 1:03:23 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 6056 ms`

**Comment by kenjkeefe** [comment]
I looked into file:/var/lib/tomcat8/webapps/webprotege/WEB-INF/classes/logback.xml to see how it was setting the logsdir and it looks like it is doing it correctly. Here is a snippet of that file.

`<?xml version="1.0" encoding="UTF-8"?>
<configuration scan="true" scanPeriod="60 seconds">

    
    <if condition='property("os.name").startsWith("Windows")'>
        <then>
            
            <property name="logsdir" value="${logs.directory:-/ProgramData/WebProtege/Logs}"/>
        </then>
        <else>
            
            <property name="logsdir" value="${logs.directory:-/var/log/webprotege}"/>
        </else>
    </if>`

**Comment by froggypaule** [comment]
Dear all,
I face the same issue. I can't see any issues in any of the log files (syslog, tomcat, catalina). It seems however that syslog is written instead of the dedicated log file : 

```

Mar 19 15:21:35 localhost tomcat9[1122]: 2020-03-19 15:21:35.003  INFO   #033[34
mProjectId{7f20918f-b301-4e9e-b84c-da9d5aca34e1} Ontology loading finished: (Loa
ded:  file:/srv/webprotege/data-store/project-data/7f20918f-b301-4e9e-b84c-da9d5
aca34e1/ontology-data/root-ontology.binary)#033[0;39m
```

is this correct ?
Many thanks!

**Comment by gebn** [comment]
We are also running into this. Looking in `/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/logback.xml`, I can see `${logsdir}` is set based on a conditional, but this seems to be skipped because Janino is not on the classpath:

    20-Apr-2020 09:12:10.923 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.41
    20-Apr-2020 09:12:10.930 SEVERE [Catalina-startStop-1] org.apache.catalina.startup.HostConfig.beforeStart Unable to create directory for deployment: [/usr/local/tomcat/conf/Catalina/localhost]
    20-Apr-2020 09:12:10.936 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/ROOT]
    09:12:16,824 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
    09:12:16,824 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
    09:12:16,825 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/logback.xml]
    09:12:16,926 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
    09:12:16,936 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [file:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/logback.xml]
    09:12:16,936 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 1 minutes
    09:12:16,939 |-ERROR in ch.qos.logback.core.joran.conditional.IfAction - Could not find Janino library on the class path. Skipping conditional processing.
    09:12:16,939 |-ERROR in ch.qos.logback.core.joran.conditional.IfAction - See also http://logback.qos.ch/codes.html#ifJanino
    09:12:16,939 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
    09:12:16,943 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [stdout]
    09:12:17,047 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
    09:12:17,050 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [webprotege]
    09:12:17,118 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1645777021 - No compression will be used
    09:12:17,119 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1645777021 - Will use the pattern logsdir_IS_UNDEFINED/webprotege.%d{yyyy-MM-dd}.log for the active file
    09:12:17,123 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern 'logsdir_IS_UNDEFINED/webprotege.%d{yyyy-MM-dd}.log'.
    09:12:17,123 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
    09:12:17,124 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Mon Apr 20 09:12:17 UTC 2020
    09:12:17,127 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[webprotege] - Active log file name: logsdir_IS_UNDEFINED/webprotege.log
    09:12:17,127 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[webprotege] - File property is set to [logsdir_IS_UNDEFINED/webprotege.log]
    09:12:17,127 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[webprotege] - Failed to create parent directories for [/usr/local/tomcat/webapps/ROOT/logsdir_IS_UNDEFINED/webprotege.log]
    09:12:17,128 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[webprotege] - openFile(logsdir_IS_UNDEFINED/webprotege.log,true) call failed. java.io.FileNotFoundException: logsdir_IS_UNDEFINED/webprotege.log (No such file or directory)
