### ISSUE TITLE
Error on specific view [OWL Entity Description Editor]

### ISSUE THREAD

**Issue by titoferreira** [protegeproject/webprotege#658]
Hi,

I have followed the instructions for deploying a server of webprotege locally following the link from github.

Everything works fine except the portlet "OWL Entity Description Editor" that returns the following error on the console and doens't work at all:

java.lang.RuntimeException: null
        at edu.stanford.bmir.protege.web.server.frame.GetManchesterSyntaxFrameActionHandler.execute(GetManchesterSyntaxFrameActionHandler.java:60)
        at edu.stanford.bmir.protege.web.server.frame.GetManchesterSyntaxFrameActionHandler.execute(GetManchesterSyntaxFrameActionHandler.java:25)
        at edu.stanford.bmir.protege.web.server.dispatch.impl.DispatchServiceExecutorImpl.execAction(DispatchServiceExecutorImpl.java:136)
        at edu.stanford.bmir.protege.web.server.dispatch.impl.DispatchServiceExecutorImpl.execBatchAction(DispatchServiceExecutorImpl.java:98)
        at edu.stanford.bmir.protege.web.server.dispatch.impl.DispatchServiceExecutorImpl.execute(DispatchServiceExecutorImpl.java:86)
        at edu.stanford.bmir.protege.web.server.dispatch.DispatchServlet.executeAction(DispatchServlet.java:49)
        at jdk.internal.reflect.GeneratedMethodAccessor61.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
        at edu.stanford.bmir.protege.web.server.app.WebProtegeRemoteServiceServlet.processCall(WebProtegeRemoteServiceServlet.java:64)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
        at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at edu.stanford.bmir.protege.web.server.filter.WebProtegeWebAppFilter.doFilter(WebProtegeWebAppFilter.java:75)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1747)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)

Am I missing some configuration step?

I am using the last version of web protege from github.

Thanks in advance for your help/support.

**Comment by michael-john-fu** [comment]
:wave: seeing the same thing -- potentially this change is related?

https://github.com/protegeproject/webprotege/commit/382b1a209bea70752cb69a1d682b68161519ba74#diff-51cbb1836354381d4efaca751f4423d5R51

**Comment by jhgoodwin** [comment]
@matthewhorridge I tried to see if it was possible to back out just enough of the edits to allow the commented out code to be run, but there are so many changes I couldn't figure it out. Do you have any suggestions of how to bring back the functionality of the src/main/java/edu/stanford/bmir/protege/web/server/frame/GetManchesterSyntaxFrameActionHandler.java ?

Alternatively, do you have any suggestions of how someone could edit axiom properties?

For example, I have:
![image](https://user-images.githubusercontent.com/2154552/89049030-9de91800-d31e-11ea-885d-822168362efb.png)

The part that I am interested in is the annotations on the biologicalTheme property being set to biological_theme_autophagy which were set using a turtle syntax on my ontology, then imported. Like this:
```turtle
[ rdf:type owl:Axiom ;
   owl:annotatedSource :lipid_carnitine ;
   owl:annotatedProperty :biologicalTheme ;
   owl:annotatedTarget :biological_theme_autophagy ;
   :confidence :confidence_strongly ;
   rdfs:comment "This is a test comment on the biological theme autophagy property which was added to the carnitine lipid"
 ] .
```
Without some easy way to add metadata to normal properties, I am quite dead in the water.

Any advice is welcome.

**Comment by matthewhorridge** [comment]
@jhgoodwin so sorry about this.  Will look into it asap.

**Comment by matthewhorridge** [comment]
@titoferreira report and @michael-john-fu for the heads-up.  Looking into a fix.

**Comment by jhgoodwin** [comment]
Hopefully this will help you.
I recorded an animated image (had to split it into 2 parts for github) of what I'm doing. If you want more details, I'd be glad to share code, data, whatnot.

![webprotege_ontology_testing_part1](https://user-images.githubusercontent.com/2154552/89065754-45277880-d33a-11ea-923a-73d47d96dec8.gif)
![webprotege_ontology_testing_part2](https://user-images.githubusercontent.com/2154552/89065786-507aa400-d33a-11ea-9d0d-6b7915d83a28.gif)

**Comment by matthewhorridge** [comment]
This issue is fixed now.  The fix is available on webprotege.stanford.edu and in release 4.0.2.

**Comment by jhgoodwin** [comment]
Thanks @matthewhorridge I'll be sure to check it out this weekend.
