### ISSUE TITLE
WebProtégé is not configured properly error, maybe related to logsdir_IS_UNDEFINED

### ISSUE THREAD

**Issue by santiagorr** [protegeproject/webprotege#661]
This could duplicate #640, but since that bug has no detailed information, I am opening a new one just in case it's an unrelated issue.

I have installed WebProtégé 4.0.0 Beta-1 and Beta-2 following the published instructions, on Debian 10, with Oracle Java and MongoDB 4.2.3. When accessing webprotégé, I get a "WebProtégé is not configured properly" error on top of the page. Also, I don't get see the **Create New Project** button that I can use on webprotege.stanford.edu (I mean, I can login an even create new accounts).

The only error that I see on the logs that could be related is this:

```
14:12:23,208 |-INFO in ch.qos.logback.core.FileAppender[webprotege] - File property is set to [logsdir_IS_UNDEFINED/webprotege.log]                                                    
14:12:23,216 |-ERROR in ch.qos.logback.core.FileAppender[webprotege] - Failed to create parent directories for [/var/lib/tomcat9/logsdir_IS_UNDEFINED/webprotege.log]                  
14:12:23,218 |-ERROR in ch.qos.logback.core.FileAppender[webprotege] - openFile(logsdir_IS_UNDEFINED/webprotege.log,true) call failed. java.io.FileNotFoundException: logsdir_IS_UNDEFIN
ED/webprotege.log (No such file or directory)                                                                        
        at java.io.FileNotFoundException: logsdir_IS_UNDEFINED/webprotege.log (No such file or directory)                                                                              
        at         at java.base/java.io.FileOutputStream.open0(Native Method)                                                                                                          
        at         at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)                                                                                               
        at         at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)                                                                                             
        at         at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)                                                                 
        at         at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:204)                                                                                                  
        at         at ch.qos.logback.core.FileAppender.start(FileAppender.java:127)                                                                                                    
        at         at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)                                                                                       
        at         at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)                                                                                    
        at         at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)                                                                                       
        at         at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)                                                                                       
        at         at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)                                                                                              
        at         at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)                                                                           
        at         at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)                                                                          
        at         at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)                                                                           
        at         at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
        at         at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)                                                                   
        at         at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)                                                                           
...
```

Any idea?

I have tried including `logs.directory=/var/log/webprotege` in webprotege.properties with same results. Tomcat has write access to `/var/log/webprotege`, and I've also include it in the systemd unit override, as you can read in #660.

Thanks in advance,

 -- Santiago

More information about the environment:

Server version name:   Apache Tomcat/9.0.16 (Debian)                                                                                      
Server built:          Jun 13 2019 21:26:12 UTC                                                                                            
Server version number: 9.0.16.0                                                                                                           
OS Name:               Linux                                                                                                              
Architecture:          amd64                                                                                                              
Java Home:             /usr/lib/jvm/jdk-11.0.6                                                                                            
JVM Version:           11.0.6+8-LTS                                                                                                       
JVM Vendor:            Oracle Corporation

**Comment by kenjkeefe** [comment]
I am having the same problem on a Ubuntu 16.04 machine running Tomcat 8, OpenJDK 11.0.5, MongoDB 4.2.3. I installed the janino library using "sudo apt-get install janino" which installed janino 2.7.0. /var/log/webprotege is owned by tomcat8:tomcat8 with full permissions for the user.

I tried adding "logs.directory=/var/log/webprotege" to /etc/webprotege/webprotege.properties.

I'm out of ideas. Here is a full output from catalina.out:

`Feb 25, 2020 5:52:06 PM org.apache.coyote.AbstractProtocol pause
INFO: Pausing ProtocolHandler ["http-nio-8081"]
Feb 25, 2020 5:52:06 PM org.apache.catalina.core.StandardService stopInternal
INFO: Stopping service Catalina
Feb 25, 2020 5:52:06 PM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["http-nio-8081"]
Feb 25, 2020 5:52:07 PM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["http-nio-8081"]
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat8/common/classes], exists: [false], isDirectory: [false], canRead: [false]
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat8/common], exists: [false], isDirectory: [false], canRead: [false]
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat8/server/classes], exists: [false], isDirectory: [false], canRead: [false]
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat8/server], exists: [false], isDirectory: [false], canRead: [false]
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat8/shared/classes], exists: [false], isDirectory: [false], canRead: [false]
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat8/shared], exists: [false], isDirectory: [false], canRead: [false]
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server version:        Apache Tomcat/8.0.32 (Ubuntu)
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server built:          Jan 24 2020 16:24:30 UTC
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server number:         8.0.32.0
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Name:               Linux
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Version:            4.4.0-174-generic
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Architecture:          amd64
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Version:           1.8.0_242-8u242-b08-0ubuntu3~16.04-b08
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Vendor:            Private Build
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_BASE:         /var/lib/tomcat8
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_HOME:         /usr/share/tomcat8
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.util.logging.config.file=/var/lib/tomcat8/conf/logging.properties
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.awt.headless=true
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Xmx128m
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -XX:+UseConcMarkSweepGC
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dfile.encoding=UTF-8
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dfile.encoding=UTF-8
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.endorsed.dirs=/usr/share/tomcat8/endorsed
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dcatalina.base=/var/lib/tomcat8
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dcatalina.home=/usr/share/tomcat8
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.io.tmpdir=/tmp/tomcat8-tomcat8-tmp
Feb 25, 2020 5:52:07 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8081"]
Feb 25, 2020 5:52:07 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
Feb 25, 2020 5:52:07 PM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 568 ms
Feb 25, 2020 5:52:08 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
Feb 25, 2020 5:52:08 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.0.32 (Ubuntu)
Feb 25, 2020 5:52:08 PM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deploying configuration descriptor /etc/tomcat8/Catalina/localhost/manager.xml
Feb 25, 2020 5:52:08 PM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Feb 25, 2020 5:52:08 PM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deployment of configuration descriptor /etc/tomcat8/Catalina/localhost/manager.xml has finished in 798 ms
Feb 25, 2020 5:52:08 PM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deploying configuration descriptor /etc/tomcat8/Catalina/localhost/host-manager.xml
Feb 25, 2020 5:52:09 PM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Feb 25, 2020 5:52:09 PM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deployment of configuration descriptor /etc/tomcat8/Catalina/localhost/host-manager.xml has finished in 335 ms
Feb 25, 2020 5:52:09 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat8/webapps/webprotege.war
Feb 25, 2020 5:52:13 PM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
17:52:13,935 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
17:52:13,936 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
17:52:13,936 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/var/lib/tomcat8/webapps/webprotege/WEB-INF/classes/logback.xml]
17:52:14,015 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
17:52:14,027 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [file:/var/lib/tomcat8/webapps/webprotege/WEB-INF/classes/logback.xml] 
17:52:14,027 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 1 minutes
17:52:14,031 |-ERROR in ch.qos.logback.core.joran.conditional.IfAction - Could not find Janino library on the class path. Skipping conditional processing.
17:52:14,031 |-ERROR in ch.qos.logback.core.joran.conditional.IfAction - See also http://logback.qos.ch/codes.html#ifJanino
17:52:14,032 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
17:52:14,037 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [stdout]
17:52:14,081 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
17:52:14,084 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [webprotege]
17:52:14,093 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1885419310 - No compression will be used
17:52:14,094 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1885419310 - Will use the pattern logsdir_IS_UNDEFINED/webprotege.%d{yyyy-MM-dd}.log for the active file
17:52:14,099 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern 'logsdir_IS_UNDEFINED/webprotege.%d{yyyy-MM-dd}.log'.
17:52:14,099 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
17:52:14,100 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Tue Feb 25 17:52:14 CST 2020
17:52:14,103 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[webprotege] - Active log file name: logsdir_IS_UNDEFINED/webprotege.log
17:52:14,103 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[webprotege] - File property is set to [logsdir_IS_UNDEFINED/webprotege.log]
17:52:14,104 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[webprotege] - Failed to create parent directories for [/var/lib/tomcat8/logsdir_IS_UNDEFINED/webprotege.log]
17:52:14,104 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[webprotege] - openFile(logsdir_IS_UNDEFINED/webprotege.log,true) call failed. java.io.FileNotFoundException: logsdir_IS_UNDEFINED/webprotege.log (No such file or directory)
	at java.io.FileNotFoundException: logsdir_IS_UNDEFINED/webprotege.log (No such file or directory)
	at 	at java.io.FileOutputStream.open0(Native Method)
	at 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:204)
	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:127)
	at 	at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:100)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:128)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:107)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:295)
	at 	at ch.qos.logback.classic.util.StatusViaSLF4JLoggerFactory.addStatus(StatusViaSLF4JLoggerFactory.java:32)
	at 	at ch.qos.logback.classic.util.StatusViaSLF4JLoggerFactory.addInfo(StatusViaSLF4JLoggerFactory.java:20)
	at 	at ch.qos.logback.classic.servlet.LogbackServletContainerInitializer.onStartup(LogbackServletContainerInitializer.java:26)
	at 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5253)
	at 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:939)
	at 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1812)
	at 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at 	at java.lang.Thread.run(Thread.java:748)
17:52:14,104 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
17:52:14,104 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [webprotege-all]
17:52:14,105 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1657122973 - No compression will be used
17:52:14,105 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1657122973 - Will use the pattern logsdir_IS_UNDEFINED/webprotege-all.%d{yyyy-MM-dd}.log for the active file
17:52:14,105 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern 'logsdir_IS_UNDEFINED/webprotege-all.%d{yyyy-MM-dd}.log'.
17:52:14,105 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
17:52:14,106 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Tue Feb 25 17:52:14 CST 2020
17:52:14,107 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[webprotege-all] - Active log file name: logsdir_IS_UNDEFINED/webprotege-all.log
17:52:14,107 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[webprotege-all] - File property is set to [logsdir_IS_UNDEFINED/webprotege-all.log]
17:52:14,107 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[webprotege-all] - Failed to create parent directories for [/var/lib/tomcat8/logsdir_IS_UNDEFINED/webprotege-all.log]
17:52:14,107 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[webprotege-all] - openFile(logsdir_IS_UNDEFINED/webprotege-all.log,true) call failed. java.io.FileNotFoundException: logsdir_IS_UNDEFINED/webprotege-all.log (No such file or directory)
	at java.io.FileNotFoundException: logsdir_IS_UNDEFINED/webprotege-all.log (No such file or directory)
	at 	at java.io.FileOutputStream.open0(Native Method)
	at 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:204)
	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:127)
	at 	at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:100)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:128)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:107)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:295)
	at 	at ch.qos.logback.classic.util.StatusViaSLF4JLoggerFactory.addStatus(StatusViaSLF4JLoggerFactory.java:32)
	at 	at ch.qos.logback.classic.util.StatusViaSLF4JLoggerFactory.addInfo(StatusViaSLF4JLoggerFactory.java:20)
	at 	at ch.qos.logback.classic.servlet.LogbackServletContainerInitializer.onStartup(LogbackServletContainerInitializer.java:26)
	at 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5253)
	at 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:939)
	at 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1812)
	at 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at 	at java.lang.Thread.run(Thread.java:748)
17:52:14,107 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [edu.stanford.bmir.protege.web] to INFO
17:52:14,107 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [webprotege] to Logger[edu.stanford.bmir.protege.web]
17:52:14,108 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [stdout] to Logger[edu.stanford.bmir.protege.web]
17:52:14,108 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@52:68 - no applicable action for [turboFilter], current ElementPath  is [[configuration][turboFilter]]
17:52:14,109 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@53:15 - no applicable action for [Name], current ElementPath  is [[configuration][turboFilter][Name]]
17:52:14,109 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@54:17 - no applicable action for [Marker], current ElementPath  is [[configuration][turboFilter][Marker]]
17:52:14,109 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@55:18 - no applicable action for [OnMatch], current ElementPath  is [[configuration][turboFilter][OnMatch]]
17:52:14,109 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
17:52:14,109 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [webprotege-all] to Logger[ROOT]
17:52:14,109 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
17:52:14,110 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@1be423ac - Registering current configuration as safe fallback point

Feb 25, 2020 5:52:14 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
Feb 25, 2020 5:52:14 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/webprotege] startup failed due to previous errors
Feb 25, 2020 5:52:14 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
WARNING: The web application [webprotege] appears to have started a thread named [logback-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)
Feb 25, 2020 5:52:14 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /var/lib/tomcat8/webapps/webprotege.war has finished in 4,968 ms
Feb 25, 2020 5:52:14 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-8081"]
Feb 25, 2020 5:52:14 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 6170 ms`
