### ISSUE TITLE
webprotege-client build error

### ISSUE THREAD

**Issue by OyvindLGjesdal** [protegeproject/webprotege#687]
Hello,

I'm trying to build webprotege from the forms branch. I tried building with openjdk-11 and openjdk-14 in centos7.

I used the skipTest due to https://github.com/protegeproject/webprotege/issues/339

```
mvn clean package  -DskipTests
```
```
[INFO] webprotege ......................................... SUCCESS [  2.200 s]
[INFO] webprotege-shared-core ............................. SUCCESS [  8.827 s]
[INFO] webprotege-shared .................................. SUCCESS [ 34.852 s]
[INFO] webprotege-server-core ............................. SUCCESS [ 57.385 s]
[INFO] webprotege-client .................................. FAILURE [16:41 min]
[INFO] webprotege-server .................................. SKIPPED
[INFO] webprotege-cli ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18:28 min
[INFO] Finished at: 2020-05-23T22:37:12+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0.0:compile (default-compile) on project webprotege-client: GWT exited with status 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :webprotege-client
```
```
[centos@webprotege-test webprotege]$ export MAVEN_OPTS="-Xmx3000M -Dgwt.extraJvmArgs=-Xms1g -Xmx3000M"
```
I tried to increase the options, but I have not had any luck so far. I'm unsure if thats because the arguments are not used, or if I haven't used a large enough VM and increased the OPTS enough to complete the build.

**Comment by OyvindLGjesdal** [comment]
Closing this issue, was succesfully built from IntelliJ locally with more RAM available.

I see I forgot the actual errors:
```
[INFO]    Compilation succeeded -- 929.427s
[INFO] Linking into /tmp/webprotege/webprotege-client/target/webprotege-client-4.0.0-beta-3-SNAPSHOT/webprotege
[INFO]    Invoking Linker Cross-Site-Iframe
[INFO]       [ERROR] Failed to link
[INFO] java.lang.OutOfMemoryError: Java heap space
[INFO] 	at java.base/java.util.Arrays.copyOf(Arrays.java:3536)
[INFO] 	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:227)
[INFO] 	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:593)
[INFO] 	at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
[INFO] 	at com.google.gwt.core.linker.CrossSiteIframeLinker.wrapPrimaryFragment(CrossSiteIframeLinker.java:700)
[INFO] 	at com.google.gwt.core.ext.linker.impl.SelectionScriptLinker.generatePrimaryFragmentString(SelectionScriptLinker.java:411)
[INFO] 	at com.google.gwt.core.ext.linker.impl.SelectionScriptLinker.generatePrimaryFragment(SelectionScriptLinker.java:386)
[INFO] 	at com.google.gwt.core.ext.linker.impl.SelectionScriptLinker.doEmitCompilation(SelectionScriptLinker.java:254)
[INFO] 	at com.google.gwt.core.ext.linker.impl.SelectionScriptLinker.link(SelectionScriptLinker.java:196)
[INFO] 	at com.google.gwt.core.ext.linker.impl.StandardLinkerContext.invokeLinkForOnePermutation(StandardLinkerContext.java:384)
[INFO] 	at com.google.gwt.dev.Link.finishPermutation(Link.java:483)
[INFO] 	at com.google.gwt.dev.Link.doSimulatedShardingLink(Link.java:445)
[INFO] 	at com.google.gwt.dev.Link.link(Link.java:178)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:244)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:155)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:144)
[INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:118)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
[INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:125)
[INFO]          [ERROR] Out of memory; to increase the amount of memory, use the -Xmx flag at startup (java -Xmx128M ...)
```

**Comment by KMax** [comment]
@OyvindLGjesdal Can you share your settings?

I tried to build it with `mvn clean package -DskipTests -Dgwt.localWorkers=2` and

```
<plugin>
  <groupId>net.ltgt.gwt.maven</groupId>
  <artifactId>gwt-maven-plugin</artifactId>
  <version>1.0.0</version>
  <extensions>true</extensions>
  <configuration>
    ...
    <jvmArgs>
      <jvmArg>-Xms512m</jvmArg>
      <jvmArg>-Xmx768m</jvmArg>
    </jvmArgs>
  </configuration>
</plugin>
```

on a machine with 8Gb. But still it fails with the Out of memory error.

**Comment by KMax** [comment]
After several hours of strangling I manage to build the master branch in CI with the following configurations:

VM:
  - RAM: 8Gb
  - check that the CI agent (if used) has the -Xmx setting set

Command: `MAVEN_OPTS=-Xmx512m mvn clean package -DskipTests -Dgwt.localWorkers=1`

pom.xml:

```
<jvmArgs>
  <jvmArg>-Xms512m</jvmArg>
  <jvmArg>-Xmx2048m</jvmArg>
</jvmArgs>
```

**Comment by OyvindLGjesdal** [comment]
Thank you for posting your solution @KMax 
I  succesfully built it with intellij, without tweaking anything, but had not managed to get a CI build running, which I now have :)

I added your jvmArgs in `.mvn/jvm.config`
