### ISSUE TITLE
Error when Creating Admin Account

### ISSUE THREAD

**Issue by meerapatelmd** [protegeproject/webprotege#746]
The WebApp works great up until I attempt to create an administrator account using the jar file. I tried 3 different version, including the beta with the same results. I am trying to stand this up on a local server. 

```
$ java -jar webprotege-cli-4.0.0.jar create-admin-account
Exception in thread "main" java.lang.ExceptionInInitializerError
	at net.sf.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:166)
	at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216)
	at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:144)
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:116)
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:108)
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:104)
	at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:69)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at org.mongodb.morphia.mapping.lazy.LazyFeatureDependencies.testDependencyFullFilled(LazyFeatureDependencies.java:42)
	at org.mongodb.morphia.mapping.lazy.LazyFeatureDependencies.createDefaultProxyFactory(LazyFeatureDependencies.java:57)
	at org.mongodb.morphia.mapping.Mapper.<init>(Mapper.java:102)
	at org.mongodb.morphia.Morphia.<init>(Morphia.java:47)
	at edu.stanford.bmir.protege.web.server.persistence.MorphiaProvider.get(MorphiaProvider.java:82)
	at edu.stanford.bmir.protege.web.server.cmdline.SetupTools.getMorphia(SetupTools.java:141)
	at edu.stanford.bmir.protege.web.server.cmdline.SetupTools.main(SetupTools.java:118)
	at edu.stanford.bmir.protege.web.server.cmdline.CreateAdminAccountCmd.run(CreateAdminAccountCmd.java:17)
	at edu.stanford.bmir.protege.web.server.cmdline.WebProtegeCli.run(WebProtegeCli.java:72)
	at edu.stanford.bmir.protege.web.server.cmdline.WebProtegeCli.main(WebProtegeCli.java:83)
```

**Comment by meerapatelmd** [comment]
Fixed the problem - 
Had to point to Java11 since the default path was set to version 16.
```
/usr/libexec/java_home -v 1/usr/libexec/java_home -v 11 --exec java webprotege-cli-4.0.0.jar create-admin-account
```

**Comment by xzssyy** [comment]
Thanks. I change java16 to java11 then it runs correctly : )
