### ISSUE TITLE
IllegalArgumentException: null lang in AnnotationAssertionPathDictionaryLanguage

### ISSUE THREAD

**Issue by wolfch-elsevier** [protegeproject/webprotege#765]
At Elsevier, we are working with the [version-5](https://github.com/protegeproject/webprotege/tree/version-5) branch of the code. Today, we encountered an error when adding a display name property in the Display Name Settings section of Project Settings. If we add an instance of annotation property with "Annotation path" with "Synonym/label" but forget to put a value in the "lang" field as shown here:
![image](https://user-images.githubusercontent.com/57952821/168191351-3b7c36f6-11eb-490d-8a73-21dd9ab669de.png)

...we get an error dialog which pops up, looking like this:
![image](https://user-images.githubusercontent.com/57952821/168191469-25e20ddb-10d8-431d-8e8f-26753e3c3fa0.png)

Updating a project's forms in a certain way renders the entire project list inoperative due to:
```
java.lang.IllegalArgumentException: Cannot construct instance of 
`edu.stanford.bmir.protege.web.shared.shortform.AnnotationAssertionPathDictionaryLanguage`, 
problem: Null lang at:
[Source: UNKNOWN; line: -1, column: -1] 
(through reference chain: 
 edu.stanford.bmir.protege.web.shared.project.ProjectDetails["defaultDisplayNameSettings"]
 -> edu.stanford.bmir.protege.web.shared.lang.DisplayNameSettings["primaryDisplayNameLanguages"])
 ```

This corruption in just one project renders the project list inoperative and the only way to open any project is if the full URL is known/bookmarked including the `projectId`.
### Steps to Reproduce

1. Log intio webprotege
2. open a project
3.  Navigate to `Project`->`Settings` in the top right
4. Scroll down to the `Display Name Settings` section
5. Add a new entry (see plus sign at bottom of section)
6. Enter annotation property name, leave `lang` blank (that blank `lang` causes the issue
7. Select "Apply" button in the bottom right of the settings page

Full stack trace follows:
```java
java.lang.IllegalArgumentException: Cannot construct instance of `edu.stanford.bmir.protege.web.shared.shortform.AnnotationAssertionPathDictionaryLanguage`, problem: Null lang
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: edu.stanford.bmir.protege.web.shared.project.ProjectDetails["defaultDisplayNameSettings"]->edu.stanford.bmir.protege.web.shared.lang.DisplayNameSettings["primaryDisplayNameLanguages"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4133)
	at edu.stanford.bmir.protege.web.server.project.ProjectDetailsRepository.lambda$findOneFromDb$1(ProjectDetailsRepository.java:106)
	at java.base/java.util.Optional.map(Optional.java:265)
	at edu.stanford.bmir.protege.web.server.project.ProjectDetailsRepository.findOneFromDb(ProjectDetailsRepository.java:106)
	at edu.stanford.bmir.protege.web.server.project.ProjectDetailsRepository.findOneFromDbOrNull(ProjectDetailsRepository.java:98)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.lambda$new$0(BoundedLocalCache.java:3670)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2337)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2335)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2318)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:111)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:66)
	at edu.stanford.bmir.protege.web.server.project.ProjectDetailsRepository.findOne(ProjectDetailsRepository.java:112)
	at edu.stanford.bmir.protege.web.server.permissions.ProjectPermissionsManagerImpl.lambda$getReadableProjects$0(ProjectPermissionsManagerImpl.java:46)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at edu.stanford.bmir.protege.web.server.permissions.ProjectPermissionsManagerImpl.lambda$getReadableProjects$1(ProjectPermissionsManagerImpl.java:44)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at edu.stanford.bmir.protege.web.server.permissions.ProjectPermissionsManagerImpl.getReadableProjects(ProjectPermissionsManagerImpl.java:42)
	at edu.stanford.bmir.protege.web.server.dispatch.handlers.GetAvailableProjectsHandler.execute(GetAvailableProjectsHandler.java:74)
	at edu.stanford.bmir.protege.web.server.dispatch.handlers.GetAvailableProjectsHandler.execute(GetAvailableProjectsHandler.java:35)
	at edu.stanford.bmir.protege.web.server.dispatch.impl.DispatchServiceExecutorImpl.execAction(DispatchServiceExecutorImpl.java:136)
	at edu.stanford.bmir.protege.web.server.dispatch.impl.DispatchServiceExecutorImpl.execute(DispatchServiceExecutorImpl.java:89)
	at edu.stanford.bmir.protege.web.server.dispatch.DispatchServlet.executeAction(DispatchServlet.java:57)
	at jdk.internal.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
```

**Comment by matthewhorridge** [comment]
Fixed by the PR on version-5
