### ISSUE TITLE
Ontology download failed

### ISSUE THREAD

**Issue by chihpoc** [protegeproject/webprotege#775]
**Describe the bug**
**Download** project errors

**To Reproduce**
1. Go to the project list at https://webprotege.stanford.edu/#projects/list
2. Click the menu button for the project of interest
3. Select **Download** from the popup menu
4. See the error below

```
WebProtege Initialization Error
An error occurred during the initialization of WebProtege which prevented WebProtege from starting.

Error Message
java.nio.file.NoSuchFileException: /srv/protege/webprotege-data/data-store/project-data/0b6dcf4c-0ed4-4b80-9955-3117cd6333a2/change-data/change-data.binary
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:156)
	at edu.stanford.bmir.protege.web.server.revision.HeadRevisionNumberFinder.getHeadRevisionNumber(HeadRevisionNumberFinder.java:50)
	at edu.stanford.bmir.protege.web.server.download.ProjectDownloadService.getHeadRevisionNumber(ProjectDownloadService.java:214)
	at edu.stanford.bmir.protege.web.server.download.ProjectDownloadService.downloadProject(ProjectDownloadService.java:84)
	at edu.stanford.bmir.protege.web.server.download.ProjectDownloadServlet.startProjectDownload(ProjectDownloadServlet.java:91)
	at edu.stanford.bmir.protege.web.server.download.ProjectDownloadServlet.doGet(ProjectDownloadServlet.java:81)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at edu.stanford.bmir.protege.web.server.filter.WebProtegeWebAppFilter.doFilter(WebProtegeWebAppFilter.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:498)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2549)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2538)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Expected behavior**
Expect to export/download an ontology

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome, Safari
 - Version: most recent

**Additional context**
None

**Comment by OtsoHelenius-Ubigu** [comment]
I encountered the same bug and as can be deduced from NoSuchFileException, it occurs when an ontology has been created but it contains no resources (can be reproduced by creating an empty ontology).
